### ISSUE TITLE
Invalid access token when using plugin

### ISSUE THREAD

**Issue by davetao** [contentful/cf-generator-intellij#1]
Hello.
I have been trouble giving access to the plugin inside Android Studio.
I enter the access token and click login. It produces the following result.

![screen shot 2015-07-28 at 13 16 42](https://cloud.githubusercontent.com/assets/4438069/8931010/f68c0ce8-352a-11e5-8a8f-c6e70c210bee.png)

**Comment by tomxor** [comment]
Are you sure you're using a CMA access token and not a CDA one?

If not, you can get the CMA token here: https://www.contentful.com/developers/docs/references/authentication/#the-management-api

**Comment by davetao** [comment]
Thank you very much, that works. This distinction will be useful in the readme.md

**Comment by tomxor** [comment]
:+1: glad it worked out, I'll make sure to add a note in the documentation.
